parameters:
  buildConfiguration: ''
  projects: ''
  strategies: []

jobs:
  - job: UnitTest
    displayName: Run unit tests
    strategy:
      matrix:
        ${{ each strategy in parameters.strategies }}:
          ${{ each pair in strategy }}:
            ${{ pair.key }}:
              VM_IMAGE: ${{ pair.value }}
    pool:
      vmImage: $(VM_IMAGE)
    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: 6.0.x
      - pwsh: >
          dotnet test
          --verbosity normal
          --configuration ${{ parameters.buildConfiguration }}
          --logger "trx;LogFileName=testresults.trx"
          ${{ parameters.projects }}
        displayName: Execute unit tests
      - task: PublishTestResults@2
        displayName: Publish test results
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: "**/*.trx"
          mergeTestResults: true
          configuration: ${{ parameters.buildConfiguration }}
