trigger: none

variables:
  - template: variables.yml

stages:
  - stage: IntegrationTests
    displayName: 🧪 Full set of integration tests
    jobs:
      - template: jobs/run-integration-tests.yml
        parameters:
          vmImage: $(vmImage)
          buildConfiguration: $(buildConfiguration)
          projects: $(integrationTestsProject)
          netSdkVersion: $(netSdkVersion)
